name: Generate RSS Feed
on:
  schedule:
    - cron: "0 */6 * * *" # Toutes les 6 heures
  workflow_dispatch: # Pour permettre l'exécution manuelle
  push: # Pour tester lors des push
    branches:
      - main

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate RSS
        run: python3.11 rss_generator.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
